version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  web:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db