# Generated by Django 3.2.3 on 2021-05-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_account', '0002_spotifydata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifydata',
            name='auth_code',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='spotifydata',
            name='auth_token',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='spotifydata',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
